{{- if and .Values.controlPlane.enabled .Values.controlPlane.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "telemetry-fabric.controlPlaneName" . }}
  labels:
    {{- include "telemetry-fabric.controlPlaneLabels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.controlPlane.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "telemetry-fabric.controlPlaneName" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
