{{- if .Values.agent.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "telemetry-fabric.serviceAccountName" . }}
  labels:
    {{- include "telemetry-fabric.labels" . | nindent 4 }}
  {{- with .Values.agent.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.agent.serviceAccount.automountServiceAccountToken }}
{{- end }}
{{- if and .Values.controlPlane.enabled .Values.controlPlane.serviceAccount.create }}
{{- if .Values.agent.serviceAccount.create }}
---
{{- end }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "telemetry-fabric.controlPlaneServiceAccountName" . }}
  labels:
    {{- include "telemetry-fabric.controlPlaneLabels" . | nindent 4 }}
  {{- with .Values.controlPlane.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.controlPlane.serviceAccount.automountServiceAccountToken }}
{{- end }}
{{- if and .Values.crawler.enabled .Values.crawler.serviceAccount.create }}
{{- if or .Values.agent.serviceAccount.create (and .Values.controlPlane.enabled .Values.controlPlane.serviceAccount.create) }}
---
{{- end }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "telemetry-fabric.crawlerServiceAccountName" . }}
  labels:
    {{- include "telemetry-fabric.componentLabels" (dict "root" . "name" (include "telemetry-fabric.crawlerName" .) "component" "chain-crawler") | nindent 4 }}
  {{- with .Values.crawler.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.crawler.serviceAccount.automountServiceAccountToken }}
{{- end }}
{{- if and .Values.streamProcessor.enabled .Values.streamProcessor.serviceAccount.create }}
{{- if or .Values.agent.serviceAccount.create (and .Values.controlPlane.enabled .Values.controlPlane.serviceAccount.create) (and .Values.crawler.enabled .Values.crawler.serviceAccount.create) }}
---
{{- end }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "telemetry-fabric.streamProcessorServiceAccountName" . }}
  labels:
    {{- include "telemetry-fabric.componentLabels" (dict "root" . "name" (include "telemetry-fabric.streamProcessorName" .) "component" "stream-processor") | nindent 4 }}
  {{- with .Values.streamProcessor.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.streamProcessor.serviceAccount.automountServiceAccountToken }}
{{- end }}
