apiVersion: v1
kind: Service
metadata:
  name: {{ include "telemetry-fabric.name" . }}
  labels:
    {{- include "telemetry-fabric.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "telemetry-fabric.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: otlp-grpc
      port: {{ .Values.service.port }}
      targetPort: otlp-grpc
    - name: health
      port: {{ .Values.service.healthPort }}
      targetPort: health
