{{- if and .Values.crawler.enabled .Values.crawler.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "telemetry-fabric.crawlerName" . }}
  labels:
    {{- include "telemetry-fabric.componentLabels" (dict "root" . "name" (include "telemetry-fabric.crawlerName" .) "component" "chain-crawler") | nindent 4 }}
spec:
  minAvailable: {{ .Values.crawler.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "telemetry-fabric.crawlerName" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
{{- if and .Values.streamProcessor.enabled .Values.streamProcessor.podDisruptionBudget.enabled }}
{{- if and .Values.crawler.enabled .Values.crawler.podDisruptionBudget.enabled }}
---
{{- end }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "telemetry-fabric.streamProcessorName" . }}
  labels:
    {{- include "telemetry-fabric.componentLabels" (dict "root" . "name" (include "telemetry-fabric.streamProcessorName" .) "component" "stream-processor") | nindent 4 }}
spec:
  minAvailable: {{ .Values.streamProcessor.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "telemetry-fabric.streamProcessorName" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
