param(
    [string]$OutputRoot = "",
    [ValidateSet("Preview", "Export")]
    [string]$Mode = "Preview",
    [switch]$Clean
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot "..\..")).Path
if ([string]::IsNullOrWhiteSpace($OutputRoot)) {
    if ($Mode -eq "Export") {
        $OutputRoot = Split-Path -Parent $RepoRoot
    } else {
        $OutputRoot = Join-Path $RepoRoot ".tmp\split-preview"
    }
} elseif (-not [System.IO.Path]::IsPathRooted($OutputRoot)) {
    $OutputRoot = Join-Path $RepoRoot $OutputRoot
}

$OutputRoot = [System.IO.Path]::GetFullPath($OutputRoot)
$TmpRoot = [System.IO.Path]::GetFullPath((Join-Path $RepoRoot ".tmp"))

function Test-IsUnderPath {
    param(
        [Parameter(Mandatory = $true)][string]$Child,
        [Parameter(Mandatory = $true)][string]$Parent
    )

    $childFull = [System.IO.Path]::GetFullPath($Child).TrimEnd('\', '/')
    $parentFull = [System.IO.Path]::GetFullPath($Parent).TrimEnd('\', '/')
    return $childFull.StartsWith($parentFull + [System.IO.Path]::DirectorySeparatorChar, [System.StringComparison]::OrdinalIgnoreCase)
}

if ((Test-Path -LiteralPath $OutputRoot) -and $Clean) {
    if (-not (Test-IsUnderPath -Child $OutputRoot -Parent $TmpRoot)) {
        throw "Refusing to clean output outside .tmp: $OutputRoot. Delete or move existing sibling projects manually if needed."
    }
    Remove-Item -LiteralPath $OutputRoot -Recurse -Force
}

New-Item -ItemType Directory -Force -Path $OutputRoot | Out-Null

function Set-Utf8NoBomFile {
    param(
        [Parameter(Mandatory = $true)][string]$Path,
        [Parameter(Mandatory = $true)][AllowEmptyString()][object]$Value,
        [switch]$NoNewline
    )

    if ($Value -is [array]) {
        $text = [string]::Join([Environment]::NewLine, [string[]]$Value)
    } else {
        $text = [string]$Value
    }

    if (-not $NoNewline) {
        $text = $text + [Environment]::NewLine
    }

    $encoding = New-Object System.Text.UTF8Encoding($false)
    [System.IO.File]::WriteAllText($Path, $text, $encoding)
}

$ExcludedDirectoryNames = @(
    ".git",
    ".tmp",
    ".cache",
    ".elixir_ls",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    ".venv",
    "__pycache__",
    "_build",
    "deps",
    "dist",
    "node_modules",
    "target",
    "venv"
)

function Copy-DirectoryFiltered {
    param(
        [Parameter(Mandatory = $true)][string]$SourceDirectory,
        [Parameter(Mandatory = $true)][string]$DestinationDirectory
    )

    New-Item -ItemType Directory -Force -Path $DestinationDirectory | Out-Null

    Get-ChildItem -LiteralPath $SourceDirectory -Force | ForEach-Object {
        if ($_.PSIsContainer -and ($ExcludedDirectoryNames -contains $_.Name)) {
            return
        }

        $destinationPath = Join-Path $DestinationDirectory $_.Name
        if ($_.PSIsContainer) {
            Copy-DirectoryFiltered -SourceDirectory $_.FullName -DestinationDirectory $destinationPath
        } else {
            Copy-Item -LiteralPath $_.FullName -Destination $destinationPath -Force
        }
    }
}

function Copy-Entry {
    param(
        [Parameter(Mandatory = $true)][string]$ProjectRoot,
        [Parameter(Mandatory = $true)][string]$Source,
        [Parameter(Mandatory = $true)][string]$Destination
    )

    $sourcePath = Join-Path $RepoRoot $Source
    if (-not (Test-Path -LiteralPath $sourcePath)) {
        Write-Warning "Skipping missing path: $Source"
        return
    }

    $destPath = if ($Destination -eq ".") { $ProjectRoot } else { Join-Path $ProjectRoot $Destination }
    New-Item -ItemType Directory -Force -Path $destPath | Out-Null

    $sourceItem = Get-Item -LiteralPath $sourcePath -Force
    if ($sourceItem.PSIsContainer) {
        Copy-DirectoryFiltered -SourceDirectory $sourcePath -DestinationDirectory $destPath
        return
    }

    Copy-Item -LiteralPath $sourcePath -Destination $destPath -Force
}

function Write-ProjectReadme {
    param(
        [Parameter(Mandatory = $true)][string]$ProjectRoot,
        [Parameter(Mandatory = $true)][string]$Name,
        [Parameter(Mandatory = $true)][string]$Description
    )

    $content = @(
        "# $Name",
        "",
        $Description,
        "",
        "Generated by scripts/dev/preview-repository-split.ps1 in $Mode mode.",
        "Source repository: $RepoRoot",
        "Review CI, package publishing, and contract dependency wiring before release."
    )
    Set-Utf8NoBomFile -Path (Join-Path $ProjectRoot "SPLIT_ORIGIN.md") -Value $content
}

function Copy-CommonFiles {
    param(
        [Parameter(Mandatory = $true)][string]$ProjectRoot
    )

    foreach ($name in @("LICENSE", ".gitignore", ".gitattributes")) {
        $sourcePath = Join-Path $RepoRoot $name
        if (Test-Path -LiteralPath $sourcePath) {
            Copy-Item -LiteralPath $sourcePath -Destination $ProjectRoot -Force
        }
    }
}

function Replace-InProjectFiles {
    param(
        [Parameter(Mandatory = $true)][string]$ProjectRoot,
        [Parameter(Mandatory = $true)][string[]]$Extensions,
        [Parameter(Mandatory = $true)][string]$Pattern,
        [Parameter(Mandatory = $true)][string]$Replacement
    )

    Get-ChildItem -LiteralPath $ProjectRoot -Recurse -File -Force | Where-Object {
        $Extensions -contains $_.Extension -or $Extensions -contains $_.Name
    } | ForEach-Object {
        $text = Get-Content -LiteralPath $_.FullName -Raw
        $updated = $text -replace [regex]::Escape($Pattern), $Replacement
        if ($updated -ne $text) {
            Set-Utf8NoBomFile -Path $_.FullName -Value $updated -NoNewline
        }
    }
}

function Write-CoreMakefile {
    param([Parameter(Mandatory = $true)][string]$ProjectRoot)

    $content = @'
.PHONY: test rust-test elixir-test agent-self-test

test: rust-test elixir-test

rust-test:
	cargo test --workspace

agent-self-test:
	cargo run -p telemetry-agent -- --self-test

elixir-test:
	cd apps/control_plane && mix test
'@
    Set-Utf8NoBomFile -Path (Join-Path $ProjectRoot "Makefile") -Value $content
}

function Write-GoMakefile {
    param([Parameter(Mandatory = $true)][string]$ProjectRoot)

    $content = @'
.PHONY: test run race

test:
	go test ./...

run:
	go run ./cmd/crawler

race:
	CGO_ENABLED=1 go test -race ./...
'@
    Set-Utf8NoBomFile -Path (Join-Path $ProjectRoot "Makefile") -Value $content
}

function Write-PythonMakefile {
    param([Parameter(Mandatory = $true)][string]$ProjectRoot)

    $content = @'
PYTHON ?= python

.PHONY: install install-dev test

install:
	"$(PYTHON)" -m pip install -e .

install-dev:
	"$(PYTHON)" -m pip install -e ".[dev]"

test:
	"$(PYTHON)" -m pytest
'@
    Set-Utf8NoBomFile -Path (Join-Path $ProjectRoot "Makefile") -Value $content
}

function Write-ComputeMakefile {
    param([Parameter(Mandatory = $true)][string]$ProjectRoot)

    $content = @'
CMAKE ?= cmake
CTEST ?= ctest
CMAKE_BUILD_DIR ?= build
CMAKE_GENERATOR ?=
CMAKE_ARCH ?=
CMAKE_CONFIGURE_ARGS ?= -DACCELERATOR_ENABLE_TESTS=ON
CMAKE_BUILD_ARGS ?=
CTEST_ARGS ?= --output-on-failure
CMAKE_GENERATOR_ARG = $(if $(strip $(CMAKE_GENERATOR)),-G "$(CMAKE_GENERATOR)")
CMAKE_ARCH_ARG = $(if $(strip $(CMAKE_ARCH)),-A "$(CMAKE_ARCH)")

.PHONY: configure build test clean

configure:
	"$(CMAKE)" -S . -B "$(CMAKE_BUILD_DIR)" $(CMAKE_GENERATOR_ARG) $(CMAKE_ARCH_ARG) $(CMAKE_CONFIGURE_ARGS)

build: configure
	"$(CMAKE)" --build "$(CMAKE_BUILD_DIR)" $(CMAKE_BUILD_ARGS)

test: build
	"$(CTEST)" --test-dir "$(CMAKE_BUILD_DIR)" $(CTEST_ARGS)

clean:
	"$(CMAKE)" -E rm -rf "$(CMAKE_BUILD_DIR)"
'@
    Set-Utf8NoBomFile -Path (Join-Path $ProjectRoot "Makefile") -Value $content
}

function Write-DeployMakefile {
    param([Parameter(Mandatory = $true)][string]$ProjectRoot)

    $content = @'
COMPOSE_FILE ?= deploy/docker/docker-compose.yml
HELM_RELEASE ?= telemetry-fabric
HELM_NAMESPACE ?= observability
HELM_CHART ?= deploy/helm/telemetry-fabric
LOCAL_PROFILES ?= --profile blockchain --profile observability

.PHONY: docker-smoke deploy-local k8s-render helm-lint blockchain-smoke clickhouse-migrate kafka-topics

docker-smoke:
	bash scripts/ci_smoke_compose.sh

deploy-local:
	docker compose -f $(COMPOSE_FILE) $(LOCAL_PROFILES) up -d --build

k8s-render:
	helm template $(HELM_RELEASE) $(HELM_CHART) --namespace $(HELM_NAMESPACE)

helm-lint:
	helm lint $(HELM_CHART)

blockchain-smoke:
	docker compose -f $(COMPOSE_FILE) --profile blockchain up -d redpanda clickhouse
	docker compose -f $(COMPOSE_FILE) exec redpanda rpk cluster health --brokers=127.0.0.1:9092
	docker compose -f $(COMPOSE_FILE) exec clickhouse clickhouse-client --query "SELECT 1"

clickhouse-migrate:
	docker compose -f $(COMPOSE_FILE) --profile blockchain up -d clickhouse
	bash -lc 'for f in storage/clickhouse/migrations/*.sql; do docker compose -f "$(COMPOSE_FILE)" exec -T clickhouse clickhouse-client --multiquery < "$$f"; done'

kafka-topics:
	docker compose -f $(COMPOSE_FILE) --profile blockchain up -d redpanda
	docker compose -f $(COMPOSE_FILE) exec redpanda rpk topic create chain.events.raw chain.events.critical chain.events.important chain.events.aggregate chain.events.dead_letter chain.alerts chain.reorgs chain.node_health --brokers=127.0.0.1:9092 --if-not-exists
'@
    Set-Utf8NoBomFile -Path (Join-Path $ProjectRoot "Makefile") -Value $content
}

function Write-DeployCi {
    param([Parameter(Mandatory = $true)][string]$ProjectRoot)

    $workflowDir = Join-Path $ProjectRoot ".github\workflows"
    New-Item -ItemType Directory -Force -Path $workflowDir | Out-Null

    $content = @'
name: Deploy Assets

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  deploy-assets:
    name: Deployment Assets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker compose -f deploy/docker/docker-compose.yml config
      - uses: azure/setup-helm@v4
      - run: helm lint deploy/helm/telemetry-fabric
      - run: helm lint deploy/helm/telemetry-fabric -f deploy/helm/telemetry-fabric/values-production.example.yaml
      - run: helm template telemetry-fabric deploy/helm/telemetry-fabric --set controlPlane.enabled=true
      - run: helm template telemetry-fabric deploy/helm/telemetry-fabric -f deploy/helm/telemetry-fabric/values-production.example.yaml
      - run: |
          if helm template telemetry-fabric deploy/helm/telemetry-fabric --set controlPlane.enabled=true --set controlPlane.replicas=2; then
            echo "expected Helm validation to reject multi-replica OTP storage"
            exit 1
          fi
'@
    Set-Utf8NoBomFile -Path (Join-Path $workflowDir "ci.yml") -Value $content

    $securityContent = @'
name: Security

on:
  push:
    branches: ["main"]
  pull_request:
  schedule:
    - cron: "19 3 * * 1"

permissions:
  contents: read
  security-events: write

jobs:
  vulnerability-scan:
    name: Vulnerability Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aquasecurity/trivy-action@0.32.0
        with:
          scan-type: fs
          scan-ref: .
          severity: HIGH,CRITICAL
          ignore-unfixed: true
          format: sarif
          output: trivy-results.sarif
          exit-code: "1"
      - uses: github/codeql-action/upload-sarif@v3
        if: always() && github.event_name != 'pull_request' && hashFiles('trivy-results.sarif') != ''
        with:
          sarif_file: trivy-results.sarif
'@
    Set-Utf8NoBomFile -Path (Join-Path $workflowDir "security.yml") -Value $securityContent

    $releaseWorkflow = Join-Path $workflowDir "release.yml"
    if (Test-Path -LiteralPath $releaseWorkflow) {
        Remove-Item -LiteralPath $releaseWorkflow -Force
    }
}

function Convert-DeployProjectPaths {
    param([Parameter(Mandatory = $true)][string]$ProjectRoot)

    $compose = Join-Path $ProjectRoot "deploy\docker\docker-compose.yml"
    if (Test-Path -LiteralPath $compose) {
        $text = Get-Content -LiteralPath $compose -Raw
        $text = $text -replace "context: \.\./\.\.", "context: ../../.."
        $text = $text -replace "dockerfile: deploy/docker/control-plane\.Dockerfile", "dockerfile: telemetry-fabric-deploy/deploy/docker/control-plane.Dockerfile"
        $text = $text -replace "dockerfile: deploy/docker/telemetry-agent\.Dockerfile", "dockerfile: telemetry-fabric-deploy/deploy/docker/telemetry-agent.Dockerfile"
        Set-Utf8NoBomFile -Path $compose -Value $text -NoNewline
    }

    $controlPlaneDockerfile = Join-Path $ProjectRoot "deploy\docker\control-plane.Dockerfile"
    if (Test-Path -LiteralPath $controlPlaneDockerfile) {
        $text = Get-Content -LiteralPath $controlPlaneDockerfile -Raw
        $text = $text -replace "/workspace/apps/control_plane", "/workspace/telemetry-fabric-core/apps/control_plane"
        $text = $text -replace "COPY apps/control_plane/", "COPY telemetry-fabric-core/apps/control_plane/"
        Set-Utf8NoBomFile -Path $controlPlaneDockerfile -Value $text -NoNewline
    }

    $agentDockerfile = Join-Path $ProjectRoot "deploy\docker\telemetry-agent.Dockerfile"
    if (Test-Path -LiteralPath $agentDockerfile) {
        $text = Get-Content -LiteralPath $agentDockerfile -Raw
        $text = $text -replace "WORKDIR /workspace", "WORKDIR /workspace/telemetry-fabric-core"
        $text = $text -replace "COPY \. \.", "COPY telemetry-fabric-core ."
        Set-Utf8NoBomFile -Path $agentDockerfile -Value $text -NoNewline
    }
}

function Write-ContractsMakefile {
    param([Parameter(Mandatory = $true)][string]$ProjectRoot)

    $content = @'
.PHONY: test

test:
	@echo "Contracts project contains schemas, storage contracts, modules, and fixtures. Add buf/jsonschema compatibility checks before release."
'@
    Set-Utf8NoBomFile -Path (Join-Path $ProjectRoot "Makefile") -Value $content
}

function Invoke-ProjectPostProcess {
    param(
        [Parameter(Mandatory = $true)][string]$ProjectRoot,
        [Parameter(Mandatory = $true)][string]$Name
    )

    Copy-CommonFiles -ProjectRoot $ProjectRoot

    switch ($Name) {
        "telemetry-fabric-core" {
            Write-CoreMakefile -ProjectRoot $ProjectRoot
        }
        "telemetry-fabric-contracts" {
            Write-ContractsMakefile -ProjectRoot $ProjectRoot
        }
        "telemetry-chain-crawler-go" {
            Replace-InProjectFiles -ProjectRoot $ProjectRoot -Extensions @(".go", "go.mod", ".md") -Pattern "telemetry-fabric/services/chain-crawler-go" -Replacement "telemetry-chain-crawler-go"
            Replace-InProjectFiles -ProjectRoot $ProjectRoot -Extensions @(".md") -Pattern "cd services/chain-crawler-go" -Replacement "cd telemetry-chain-crawler-go"
            Write-GoMakefile -ProjectRoot $ProjectRoot
        }
        "telemetry-analytics-python" {
            $queryTest = Join-Path $ProjectRoot "tests\test_clickhouse_queries.py"
            if (Test-Path -LiteralPath $queryTest) {
                $text = Get-Content -LiteralPath $queryTest -Raw
                $text = $text -replace "parents\[3\]", "parents[1]"
                Set-Utf8NoBomFile -Path $queryTest -Value $text -NoNewline
            }
            Replace-InProjectFiles -ProjectRoot $ProjectRoot -Extensions @(".md", ".py") -Pattern "services\analytics-python" -Replacement "telemetry-analytics-python"
            Replace-InProjectFiles -ProjectRoot $ProjectRoot -Extensions @(".md", ".py") -Pattern "services/analytics-python" -Replacement "telemetry-analytics-python"
            Write-PythonMakefile -ProjectRoot $ProjectRoot
        }
        "telemetry-compute-accelerator" {
            Replace-InProjectFiles -ProjectRoot $ProjectRoot -Extensions @(".md", "Dockerfile") -Pattern "services/compute-accelerator" -Replacement "telemetry-compute-accelerator"
            $dockerfile = Join-Path $ProjectRoot "docker\Dockerfile"
            if (Test-Path -LiteralPath $dockerfile) {
                $text = Get-Content -LiteralPath $dockerfile -Raw
                $text = $text -replace "/workspace/telemetry-compute-accelerator", "/workspace/telemetry-compute-accelerator"
                Set-Utf8NoBomFile -Path $dockerfile -Value $text -NoNewline
            }
            Write-ComputeMakefile -ProjectRoot $ProjectRoot
        }
        "telemetry-fabric-deploy" {
            Convert-DeployProjectPaths -ProjectRoot $ProjectRoot
            Write-DeployMakefile -ProjectRoot $ProjectRoot
            Write-DeployCi -ProjectRoot $ProjectRoot
        }
    }
}

$Projects = @(
    @{
        Name = "telemetry-fabric-core"
        Description = "Rust and Elixir distributed-system core."
        Entries = @(
            @{ Source = "apps\control_plane"; Destination = "apps\control_plane" },
            @{ Source = "crates"; Destination = "crates" },
            @{ Source = "proto"; Destination = "proto" },
            @{ Source = "config"; Destination = "config" },
            @{ Source = "Cargo.toml"; Destination = "." },
            @{ Source = "Cargo.lock"; Destination = "." },
            @{ Source = "Makefile"; Destination = "." },
            @{ Source = "README.md"; Destination = "." },
            @{ Source = "LICENSE"; Destination = "." },
            @{ Source = "docs\architecture.md"; Destination = "docs" },
            @{ Source = "docs\data-plane-runtime.md"; Destination = "docs" },
            @{ Source = "docs\control-plane-hardening.md"; Destination = "docs" },
            @{ Source = "docs\development.md"; Destination = "docs" }
        )
    },
    @{
        Name = "telemetry-fabric-contracts"
        Description = "Versioned cross-service contracts, schemas, modules, and canonical fixtures."
        Entries = @(
            @{ Source = "contracts"; Destination = "contracts" },
            @{ Source = "proto"; Destination = "proto" },
            @{ Source = "storage"; Destination = "storage" },
            @{ Source = "modules"; Destination = "modules" },
            @{ Source = "tests\fixtures"; Destination = "tests\fixtures" },
            @{ Source = "docs\service-boundaries.md"; Destination = "docs" },
            @{ Source = "docs\module-system.md"; Destination = "docs" }
        )
    },
    @{
        Name = "telemetry-chain-crawler-go"
        Description = "Go blockchain crawler service."
        Entries = @(
            @{ Source = "services\chain-crawler-go"; Destination = "." },
            @{ Source = "contracts\proto\blockchain"; Destination = "contracts\proto\blockchain" },
            @{ Source = "modules\blockchain"; Destination = "modules\blockchain" },
            @{ Source = "tests\fixtures"; Destination = "tests\fixtures" },
            @{ Source = "tests\smoke\run_mock_rpc_smoke.py"; Destination = "tests\smoke" },
            @{ Source = "docs\modules"; Destination = "docs\modules" }
        )
    },
    @{
        Name = "telemetry-analytics-python"
        Description = "Python analytics, data cleaning, and feature jobs."
        Entries = @(
            @{ Source = "services\analytics-python"; Destination = "." },
            @{ Source = "storage\clickhouse\queries"; Destination = "storage\clickhouse\queries" },
            @{ Source = "contracts\examples"; Destination = "contracts\examples" },
            @{ Source = "tests\fixtures"; Destination = "tests\fixtures" },
            @{ Source = "docs\analytics"; Destination = "docs\analytics" }
        )
    },
    @{
        Name = "telemetry-compute-accelerator"
        Description = "C++ and CUDA compute accelerator service."
        Entries = @(
            @{ Source = "services\compute-accelerator"; Destination = "." },
            @{ Source = "docs\accelerator"; Destination = "docs\accelerator" }
        )
    },
    @{
        Name = "telemetry-fabric-deploy"
        Description = "Deployment, observability, and cross-project integration harness."
        Entries = @(
            @{ Source = "deploy"; Destination = "deploy" },
            @{ Source = "observability"; Destination = "observability" },
            @{ Source = "storage"; Destination = "storage" },
            @{ Source = "tests"; Destination = "tests" },
            @{ Source = "scripts"; Destination = "scripts" },
            @{ Source = "Makefile"; Destination = "." },
            @{ Source = ".github"; Destination = ".github" },
            @{ Source = "docs\operations"; Destination = "docs\operations" },
            @{ Source = "docs\service-boundaries.md"; Destination = "docs" }
        )
    }
)

foreach ($project in $Projects) {
    $projectRoot = Join-Path $OutputRoot $project.Name
    if (Test-Path -LiteralPath $projectRoot) {
        throw "Target project already exists: $projectRoot. Move it away or use a clean .tmp preview output."
    }
    New-Item -ItemType Directory -Force -Path $projectRoot | Out-Null

    foreach ($entry in $project.Entries) {
        Copy-Entry -ProjectRoot $projectRoot -Source $entry.Source -Destination $entry.Destination
    }

    Invoke-ProjectPostProcess -ProjectRoot $projectRoot -Name $project.Name
    Write-ProjectReadme -ProjectRoot $projectRoot -Name $project.Name -Description $project.Description
}

$manifest = [ordered]@{
    generated_at_utc = (Get-Date).ToUniversalTime().ToString("o")
    source_repository = $RepoRoot
    output_root = $OutputRoot
    projects = $Projects | ForEach-Object {
        [ordered]@{
            name = $_.Name
            description = $_.Description
            entries = $_.Entries
        }
    }
}

Set-Utf8NoBomFile -Path (Join-Path $OutputRoot "split-manifest.json") -Value ($manifest | ConvertTo-Json -Depth 8)

Write-Host "Split preview generated at $OutputRoot"
Get-ChildItem -LiteralPath $OutputRoot -Directory | Select-Object Name, FullName
